spring:
    application:
        name: online_chat
    mvc:
        format:
            date-time: yyyy-MM-dd HH:mm:ss
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8 #东八区
        serialization:
          write-dates-as-timestamps: false
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/online_chat
        password: 123456
        username: root
    servlet:
        multipart:
            max-file-size: 5MB
mybatis-plus:
    type-aliases-package: com.example.onaffair.online_chat.entity
    global-config:
        db-config:
            update-strategy: not_empty
    type-handlers-package: com.example.onaffair.online_chat.handler

wx:
    mini-app:
        appid: ${WX_APPID:}
        secret: ${WX_SECRET:}

ai:
    api:
        deepseek:
            key: ${DEEPSEEK_API:}
            url: https://api.deepseek.com/v1/chat/completions
            model: deepseek-chat
        VL:
            key: ${DASHSCOPE_API}
            url: https://api.siliconflow.cn/v1/chat/completions
            model: deepseek-ai/deepseek-vl2



oss:
    address: https://oss-cn-hangzhou.aliyuncs.com
    access-id: ${ALIYUN_ACCESSKEY_ID:}
    access-key: ${ALIYUN_ACCESSKEY_SECRET:}
    bucket: onaffair
    role-arn: ${ALIYUN_OSS_STS_ROLE_ARN}
    region: oss-cn-hangzhou
    urlExpire: 3600

server:
    port: 721
    address: 0.0.0.0






